spring.application.name=task-scheduler-project

#spring.datasource.url=jdbc:h2:mem:taskdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.jpa.hibernate.ddl-auto=update
#spring.main.allow-bean-definition-overriding=true
#spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://${sql_ip_private}:3306/task_scheduler_project_dev?createDatabaseIfNotExist=true&serverTimezone=Asia/Kolkata
spring.datasource.username=${sql_username}
spring.datasource.password=${sql_password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.main.allow-circular-references=true
spring.jpa.show-sql=true
sql_ip_private=localhost
sql_username=root
sql_password=root


server.port= 8081